apiVersion: apps/v1
kind: Deployment
metadata:
  name: "1010-deployment"
  namespace: "1010-demo"
spec:
  selector:
    matchLabels:
      app: "1010"
  replicas: 5
  template:
    metadata:
      labels:
        app: "1010"
    spec:
      containers:
      - image: cayo999/node-web-app
        imagePullPolicy: Always
        name: "1010"
        ports:
        - containerPort: 3000